spring.application.name=auth-service
server.port=8080

#   Database Configuration
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREE
spring.datasource.username=c##auth
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#   JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
application.security.jwt.secret-key=b69f9e70da478cccbf1f479f85e7d9372cde981520899b94fa9c4fec21d78c58
application.security.jwt.expiration=900000