package com.moneybags.statement;

import com.moneybags.statement.ApiModels.*;
import org.springframework.stereotype.Service;
import java.io.*;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.zip.*;

record StatementDocument(String accountId,String maskedNumber,String accountName,String currency,java.time.LocalDate from,java.time.LocalDate to,
                         BigDecimal opening,BigDecimal closing,List<EntryView> entries) {}
record ExportedFile(byte[] bytes,String contentType,String extension) {}

@Service
class ExportService {
    ExportedFile statement(StatementDocument d,OutputFormat f){return switch(f){case CSV->new ExportedFile(csv(d),"text/csv","csv");case XLSX->new ExportedFile(xlsx(d),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx");case PDF->new ExportedFile(pdf(lines(d)),"application/pdf","pdf");};}
    byte[] certificate(CertificateView c){return pdf(List.of("MONEYBAGS "+c.certificateType()+" CERTIFICATE","", "Account: "+c.accountId(),"Fiscal year: "+c.fiscalYear(),"Gross amount: "+c.grossAmount().amount()+" "+c.grossAmount().currency(),"Tax amount: "+c.taxAmount().amount()+" "+c.taxAmount().currency(),"Generated: "+c.generatedAt()));}
    private List<String> lines(StatementDocument d){List<String> l=new ArrayList<>(List.of("MONEYBAGS ACCOUNT STATEMENT","Account: "+d.maskedNumber()+"  "+safe(d.accountName()),"Period: "+d.from()+" to "+d.to(),"Opening balance: "+money(d.opening(),d.currency()),""));l.add("Date | Reference | Description | Debit | Credit | Balance");for(EntryView e:d.entries())l.add(e.postedAt()+" | "+e.reference()+" | "+safe(e.narration())+" | "+(e.direction()==Direction.DEBIT?e.amount().amount():"")+" | "+(e.direction()==Direction.CREDIT?e.amount().amount():"")+" | "+(e.balanceAfter()==null?"":e.balanceAfter().amount()));l.add("");l.add("Closing balance: "+money(d.closing(),d.currency()));return l;}
    private byte[] csv(StatementDocument d){StringBuilder s=new StringBuilder("Account,From,To,Opening Balance,Closing Balance,Currency\r\n");s.append(csv(d.maskedNumber())).append(',').append(d.from()).append(',').append(d.to()).append(',').append(d.opening()).append(',').append(d.closing()).append(',').append(d.currency()).append("\r\n\r\nDate,Reference,Transaction ID,Ledger Entry ID,Description,Debit,Credit,Balance,Reversal Of\r\n");for(EntryView e:d.entries())s.append(e.postedAt()).append(',').append(csv(e.reference())).append(',').append(csv(e.transactionId())).append(',').append(csv(e.ledgerEntryId())).append(',').append(csv(e.narration())).append(',').append(e.direction()==Direction.DEBIT?e.amount().amount():"").append(',').append(e.direction()==Direction.CREDIT?e.amount().amount():"").append(',').append(e.balanceAfter()==null?"":e.balanceAfter().amount()).append(',').append(csv(e.reversalOfTransactionId())).append("\r\n");return s.toString().getBytes(StandardCharsets.UTF_8);}
    private byte[] xlsx(StatementDocument d){try{ByteArrayOutputStream b=new ByteArrayOutputStream();try(ZipOutputStream z=new ZipOutputStream(b,StandardCharsets.UTF_8)){zip(z,"[Content_Types].xml","<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");zip(z,"_rels/.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");zip(z,"xl/workbook.xml","<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Statement\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");zip(z,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");zip(z,"xl/worksheets/sheet1.xml",sheet(d));}return b.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
    private String sheet(StatementDocument d){List<List<String>> rows=new ArrayList<>();rows.add(List.of("Account","From","To","Opening Balance","Closing Balance","Currency"));rows.add(List.of(d.maskedNumber(),d.from().toString(),d.to().toString(),d.opening().toPlainString(),d.closing().toPlainString(),d.currency()));rows.add(List.of());rows.add(List.of("Date","Reference","Transaction ID","Ledger Entry ID","Description","Debit","Credit","Balance","Reversal Of"));for(EntryView e:d.entries())rows.add(List.of(e.postedAt().toString(),safe(e.reference()),safe(e.transactionId()),safe(e.ledgerEntryId()),safe(e.narration()),e.direction()==Direction.DEBIT?e.amount().amount():"",e.direction()==Direction.CREDIT?e.amount().amount():"",e.balanceAfter()==null?"":e.balanceAfter().amount(),safe(e.reversalOfTransactionId())));StringBuilder x=new StringBuilder("<?xml version=\"1.0\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");int rn=1;for(List<String> r:rows){x.append("<row r=\"").append(rn++).append("\">");for(String v:r)x.append("<c t=\"inlineStr\"><is><t>").append(xml(v)).append("</t></is></c>");x.append("</row>");}return x.append("</sheetData></worksheet>").toString();}
    private byte[] pdf(List<String> all){try{List<List<String>> pages=new ArrayList<>();for(int i=0;i<all.size();i+=45)pages.add(all.subList(i,Math.min(i+45,all.size())));if(pages.isEmpty())pages.add(List.of("Moneybags"));List<byte[]> objects=new ArrayList<>();objects.add(bytes("<< /Type /Catalog /Pages 2 0 R >>"));StringBuilder kids=new StringBuilder();for(int i=0;i<pages.size();i++)kids.append(4+i*2).append(" 0 R ");objects.add(bytes("<< /Type /Pages /Kids ["+kids+"] /Count "+pages.size()+" >>"));objects.add(bytes("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"));for(int i=0;i<pages.size();i++){int content=5+i*2;objects.add(bytes("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents "+content+" 0 R >>"));StringBuilder c=new StringBuilder("BT /F1 9 Tf 40 800 Td 12 TL ");for(String line:pages.get(i))c.append('(').append(pdfEscape(line)).append(") Tj T* ");c.append("ET");byte[] cb=bytes(c.toString());objects.add(bytes("<< /Length "+cb.length+" >>\nstream\n"+c+"\nendstream"));}ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(bytes("%PDF-1.4\n"));List<Integer> offsets=new ArrayList<>();offsets.add(0);for(int i=0;i<objects.size();i++){offsets.add(out.size());out.write(bytes((i+1)+" 0 obj\n"));out.write(objects.get(i));out.write(bytes("\nendobj\n"));}int xref=out.size();out.write(bytes("xref\n0 "+(objects.size()+1)+"\n0000000000 65535 f \n"));for(int i=1;i<offsets.size();i++)out.write(bytes(String.format("%010d 00000 n \n",offsets.get(i))));out.write(bytes("trailer << /Size "+(objects.size()+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF"));return out.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
    private void zip(ZipOutputStream z,String name,String value)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(bytes(value));z.closeEntry();}
    private byte[] bytes(String s){return s.getBytes(StandardCharsets.US_ASCII);}
    private String safe(String s){return s==null?"":s;}
    private String csv(String s){String v=safe(s);return '"'+v.replace("\"","\"\"")+'"';}
    private String xml(String s){return safe(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    private String pdfEscape(String s){return safe(s).replaceAll("[^\\x20-\\x7E]","?").replace("\\","\\\\").replace("(","\\(").replace(")","\\)");}
    private String money(BigDecimal v,String c){return v.setScale(2).toPlainString()+" "+c;}
}
