server:
  port: 8086
spring:
  application:
    name: statement-service
  datasource:
    url: ${STATEMENT_DB_URL:jdbc:mysql://localhost:3306/mydb}
    username: ${STATEMENT_DB_USERNAME:root}
    password: ${STATEMENT_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info