INSERT ALL
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (1, 'SAV-REG', 'Regular Savings Account', 'DEPOSIT', 'SAVINGS', TIMESTAMP '2026-07-01 09:00:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (2, 'SAV-SENIOR', 'Senior Citizen Savings', 'DEPOSIT', 'SAVINGS', TIMESTAMP '2026-07-01 09:05:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (3, 'CUR-BASIC', 'Basic Current Account', 'DEPOSIT', 'CURRENT', TIMESTAMP '2026-07-01 09:10:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (4, 'FD-12M', '12-Month Fixed Deposit', 'DEPOSIT', 'FIXED_DEPOSIT', TIMESTAMP '2026-07-01 09:15:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (5, 'CARD-DEBIT-CLASSIC', 'Debit Card Classic', 'CARD', 'DEBIT_CARD', TIMESTAMP '2026-07-01 09:20:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (6, 'CARD-CREDIT-GOLD', 'Credit Card Gold', 'CARD', 'CREDIT_CARD', TIMESTAMP '2026-07-01 09:25:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (7, 'RD-24M', '24-Month Recurring Deposit', 'DEPOSIT', 'RECURRING_DEPOSIT', TIMESTAMP '2026-07-01 09:30:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (8, 'PL-STANDARD', 'Standard Personal Loan', 'LOAN', 'PERSONAL_LOAN', TIMESTAMP '2026-07-01 09:35:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO products (id, product_code, name, product_category, product_type, created_at, updated_at) VALUES (9, 'HL-STANDARD', 'Standard Home Loan', 'LOAN', 'HOME_LOAN', TIMESTAMP '2026-07-01 09:40:00', TIMESTAMP '2026-08-01 09:00:00')
SELECT 1 FROM dual;

INSERT ALL
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (101, 1, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:00:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (201, 2, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:05:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (301, 3, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:10:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (401, 4, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:15:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (501, 5, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:20:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (601, 6, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:25:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (701, 7, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:30:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (801, 8, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:35:00', TIMESTAMP '2026-08-01 09:00:00')
  INTO product_versions (id, product_id, version_number, status, effective_from, effective_to, created_at, updated_at) VALUES (901, 9, 1, 'ACTIVE', TIMESTAMP '2026-07-01 00:00:00', NULL, TIMESTAMP '2026-07-01 09:40:00', TIMESTAMP '2026-08-01 09:00:00')
SELECT 1 FROM dual;

INSERT ALL
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (1, 'INTEREST_RATE', 'Interest Rate', 'DECIMAL', 'PERCENT')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (2, 'MIN_BALANCE', 'Minimum Balance', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (3, 'OPENING_FEE', 'Opening Fee', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (4, 'TENURE_MONTHS', 'Tenure Months', 'INTEGER', 'MONTHS')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (5, 'MIN_DEPOSIT', 'Minimum Deposit', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (6, 'MONTHLY_MIN_INSTALLMENT', 'Monthly Minimum Installment', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (7, 'MIN_LOAN_AMOUNT', 'Minimum Loan Amount', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (8, 'MAX_LOAN_AMOUNT', 'Maximum Loan Amount', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (9, 'MAX_TENURE_MONTHS', 'Maximum Tenure Months', 'INTEGER', 'MONTHS')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (10, 'PROCESSING_FEE_PERCENT', 'Processing Fee Percent', 'DECIMAL', 'PERCENT')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (11, 'CREDIT_LIMIT_MIN', 'Minimum Credit Limit', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (12, 'CREDIT_LIMIT_MAX', 'Maximum Credit Limit', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (13, 'ANNUAL_FEE', 'Annual Fee', 'DECIMAL', 'CURRENCY')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (14, 'APR', 'Annual Percentage Rate', 'DECIMAL', 'PERCENT')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (15, 'CARD_VALIDITY_MONTHS', 'Card Validity Months', 'INTEGER', 'MONTHS')
  INTO product_attribute_definitions (id, attribute_code, display_name, data_type, unit) VALUES (16, 'CASH_HANDLING', 'Cash Handling', 'STRING', NULL)
SELECT 1 FROM dual;

INSERT ALL
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1001, 101, 1, '3.000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1002, 101, 2, '1000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1003, 101, 3, '0')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1101, 201, 1, '3.500')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1102, 201, 2, '1000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1103, 201, 3, '0')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1201, 301, 1, '0.000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1202, 301, 2, '10000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1203, 301, 3, '500')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1204, 301, 16, 'BRANCH_ONLY')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1301, 401, 1, '6.800')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1302, 401, 4, '12')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1303, 401, 5, '5000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1304, 401, 3, '0')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1401, 501, 11, '0')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1402, 501, 12, '50000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1403, 501, 13, '0')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1404, 501, 15, '60')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1501, 601, 11, '50000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1502, 601, 12, '200000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1503, 601, 13, '999')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1504, 601, 14, '36.000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1505, 601, 15, '36')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1601, 701, 1, '7.000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1602, 701, 4, '24')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1603, 701, 6, '500')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1701, 801, 1, '10.500')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1702, 801, 7, '50000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1703, 801, 8, '2000000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1704, 801, 9, '60')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1705, 801, 10, '1.000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1801, 901, 1, '8.250')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1802, 901, 7, '500000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1803, 901, 8, '50000000')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1804, 901, 9, '360')
  INTO product_version_attributes (id, product_version_id, attribute_id, attribute_value) VALUES (1805, 901, 10, '0.500')
SELECT 1 FROM dual;
